# GHN API credentials
TOKEN = fc545718-6b47-11f1-a973-aee5264794df
SHOP_ID = 200778
FROM_DISTRICT_ID = 3695
FROM_WARD_CODE = 90737
BASE_URL = https://dev-online-gateway.ghn.vn/shiip/public-api

# GHN Order Management (test environment)
GHN_ORDER_TOKEN = fc545718-6b47-11f1-a973-aee5264794df
GHN_ORDER_SHOP_ID = 200778
GHN_ORDER_URL = https://dev-online-gateway.ghn.vn/shiip/public-api
